generator: admingenerator.generator.doctrine
params:
    model: Manticora\CMSBundle\Entity\ColdfusionProxy
    namespace_prefix: Manticora
    entity_manager: ~
    concurrency_lock: ~
    bundle_name: CMSBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for CMSBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for CMSBundle
            display: [name, path, Template, RouteCollection]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: ColdfusionProxy.name }|"
            display: [name, path, Template, RouteCollection]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: ColdfusionProxy.name }|"
            display: [name, path, Template, RouteCollection]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
